# Generated by Django 5.2.7 on 2026-05-12 15:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=1, help_text='Orden en que se mostrará el desafío dentro del tema.')),
                ('video_file', models.FileField(blank=True, help_text='Archivo de video asociado a este desafío (opcional).', null=True, upload_to='challenge_videos/')),
            ],
        ),
        migrations.CreateModel(
            name='EmpathyMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gustos', models.TextField(blank=True)),
                ('problemas', models.TextField(blank=True)),
                ('miedos', models.TextField(blank=True)),
                ('contexto', models.TextField(blank=True)),
                ('hobbies', models.TextField(blank=True, null=True)),
                ('datos_extra', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_equipo', models.PositiveIntegerField()),
                ('puntaje_empatia', models.PositiveIntegerField()),
                ('puntaje_creatividad', models.PositiveIntegerField()),
                ('puntaje_comunicacion', models.PositiveIntegerField()),
                ('comentario', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(blank=True, max_length=40)),
                ('desafio_empatia', models.TextField(blank=True)),
                ('campo_creatividad', models.TextField(blank=True)),
                ('cierre', models.TextField(blank=True)),
                ('guion', models.TextField(blank=True)),
                ('sugerencias_ia', models.TextField(blank=True)),
                ('score_ai', models.PositiveSmallIntegerField(blank=True, help_text='Puntaje automático 1-5 del pitch según IA.', null=True)),
                ('tiempo_preparacion_seg', models.PositiveIntegerField(default=360)),
                ('tiempo_presentacion_seg', models.PositiveIntegerField(default=90)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumen_idea', models.TextField(blank=True)),
                ('foto_prototipo', models.ImageField(blank=True, null=True, upload_to='prototipos/')),
                ('foto_grupal', models.ImageField(blank=True, null=True, upload_to='fotos_grupales/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tablet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('codigo_acceso', models.CharField(blank=True, editable=False, max_length=16, null=True, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TabletSessionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_grupo', models.CharField(max_length=10)),
                ('tokens_empatia', models.PositiveIntegerField(default=0)),
                ('tokens_creatividad', models.PositiveIntegerField(default=0)),
                ('tokens_evaluacion', models.PositiveIntegerField(default=0)),
                ('tokens_totales', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TeamGameSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('team_id', models.CharField(db_index=True, max_length=64)),
                ('board_size', models.PositiveIntegerField(default=10)),
                ('words', models.JSONField(default=list)),
                ('soup', models.JSONField(default=list)),
                ('dict_word_position', models.JSONField(default=dict)),
                ('found_words', models.JSONField(default=list)),
                ('locked_cells', models.JSONField(default=list)),
                ('active_selections', models.JSONField(default=dict)),
                ('progress_pct', models.FloatField(default=0.0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('elapsed_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PLAYING', 'Jugando'), ('FINISHED', 'Terminado'), ('TIME_UP', 'No completo')], default='PENDING', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='TeamStageProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.CharField(choices=[('ROMPEHIELO', 'Rompehielo'), ('ETAPA1', 'Etapa 1'), ('HISTORIA', 'Historia'), ('ETAPA2', 'Etapa 2'), ('ETAPA2_MAPA', 'Mapa de empatía'), ('ETAPA3', 'Etapa 3'), ('ETAPA4', 'Etapa 4'), ('COEVALUACION', 'Coevaluación'), ('RESULTADOS', 'Resultados')], default='ROMPEHIELO', max_length=30)),
                ('current_route', models.CharField(default='rompehielo', max_length=120)),
                ('etapa1_completed', models.BooleanField(default=False)),
                ('etapa2_completed', models.BooleanField(default=False)),
                ('etapa3_completed', models.BooleanField(default=False)),
                ('etapa4_completed', models.BooleanField(default=False)),
                ('coevaluacion_completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, help_text='Imagen para mostrar en la tarjeta del tema.', null=True, upload_to='topics/')),
                ('color_hex', models.CharField(blank=True, help_text='Color asociado al tema (ej: #FFCC00).', max_length=7)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
            },
        ),
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(default=1)),
                ('titulo', models.CharField(max_length=150)),
                ('historia', models.TextField(help_text='Texto narrativo del desafío o problemática.')),
                ('personaje', models.CharField(max_length=100)),
                ('imagen_personaje', models.ImageField(blank=True, null=True, upload_to='desafios/')),
                ('duracion_min', models.PositiveSmallIntegerField(default=3)),
                ('etapa', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desafios', to='etapasJuego.challenge')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('etapa_actual', models.CharField(default='ETAPA1', max_length=20)),
                ('modo_asignacion', models.CharField(choices=[('LOGIN_RANDOM', 'Asignación automática en el login'), ('PRECONFIGURADO', 'Asignación preconfigurada por el profesor')], default='LOGIN_RANDOM', max_length=20)),
                ('estado', models.CharField(choices=[('PREPARACION', 'Preparación'), ('ACTIVA', 'Activa'), ('FINALIZADA', 'Finalizada')], default='PREPARACION', max_length=20)),
                ('duracion_etapa1_segundos', models.PositiveIntegerField(default=300)),
                ('duracion_etapa2_segundos', models.PositiveIntegerField(default=600)),
                ('duracion_etapa3_segundos', models.PositiveIntegerField(default=900)),
                ('duracion_etapa4_segundos', models.PositiveIntegerField(default=600)),
                ('qr_encuesta_url', models.URLField(blank=True, null=True)),
                ('qr_instagram_url', models.URLField(blank=True, null=True)),
                ('qr_linkedin_url', models.URLField(blank=True, null=True)),
                ('palabras_sopa', models.JSONField(blank=True, default=list, help_text='Lista de 8–12 palabras para la sopa de letras (vacío = lista por defecto).')),
                ('negociacion_orden', models.JSONField(blank=True, default=list)),
                ('negociacion_presentador_idx', models.PositiveIntegerField(default=0)),
                ('negociacion_fase', models.CharField(default='ORDEN', max_length=20)),
                ('negociacion_fase_inicio', models.DateTimeField(blank=True, null=True)),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_juego', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
