# Generated by Django 5.2.7 on 2026-05-12 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etapasJuego', '0001_initial'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones', to='login.seccionestudiantes'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='etapasJuego.gamesession'),
        ),
        migrations.AddField(
            model_name='project',
            name='desafio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='etapasJuego.challenge'),
        ),
        migrations.AddField(
            model_name='project',
            name='selected_desafio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_selected', to='etapasJuego.desafio'),
        ),
        migrations.AddField(
            model_name='pitch',
            name='proyecto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pitch', to='etapasJuego.project'),
        ),
        migrations.AddField(
            model_name='empathymap',
            name='proyecto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mapa_empatia', to='etapasJuego.project'),
        ),
        migrations.AddField(
            model_name='tablet',
            name='sesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tablets', to='etapasJuego.gamesession'),
        ),
        migrations.AddField(
            model_name='tabletsessionassignment',
            name='game_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tablet_assignments', to='etapasJuego.gamesession'),
        ),
        migrations.AddField(
            model_name='tabletsessionassignment',
            name='tablet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='etapasJuego.tablet'),
        ),
        migrations.AddField(
            model_name='team',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='etapasJuego.gamesession'),
        ),
        migrations.AddField(
            model_name='team',
            name='tablet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team', to='etapasJuego.tablet'),
        ),
        migrations.AddField(
            model_name='tabletsessionassignment',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tablet_assignment', to='etapasJuego.team'),
        ),
        migrations.AddField(
            model_name='project',
            name='equipo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto', to='etapasJuego.team'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evaluado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_recibidas', to='etapasJuego.team'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evaluador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_realizadas', to='etapasJuego.team'),
        ),
        migrations.AddField(
            model_name='teamgamesession',
            name='equipo',
            field=models.ForeignKey(blank=True, help_text='Equipo asociado a esta partida de sopa de letras (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wordsearch_sessions', to='etapasJuego.team'),
        ),
        migrations.AddField(
            model_name='teamstageprogress',
            name='game_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_progress', to='etapasJuego.gamesession'),
        ),
        migrations.AddField(
            model_name='teamstageprogress',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_progress', to='etapasJuego.project'),
        ),
        migrations.AddField(
            model_name='teamstageprogress',
            name='selected_challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='etapasJuego.challenge'),
        ),
        migrations.AddField(
            model_name='teamstageprogress',
            name='selected_desafio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='etapasJuego.desafio'),
        ),
        migrations.AddField(
            model_name='teamstageprogress',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='etapasJuego.team'),
        ),
        migrations.AddField(
            model_name='teamstageprogress',
            name='selected_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='etapasJuego.topic'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='topic',
            field=models.ForeignKey(help_text='Tema al que pertenece este desafío.', on_delete=django.db.models.deletion.PROTECT, related_name='desafios', to='etapasJuego.topic'),
        ),
        migrations.AddConstraint(
            model_name='tabletsessionassignment',
            constraint=models.UniqueConstraint(fields=('tablet', 'game_session'), name='unique_tablet_per_gamesession_assignment'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluation',
            unique_together={('sesion', 'evaluador', 'evaluado')},
        ),
    ]
