# Generated by Django 5.2.7 on 2026-05-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etapasJuego', '0019_gamesession_qr_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='gamesession',
            name='unique_gamesession_per_seccion',
        ),
        migrations.AddField(
            model_name='gamesession',
            name='estado',
            field=models.CharField(choices=[('PREPARACION', 'Preparación'), ('ACTIVA', 'Activa'), ('FINALIZADA', 'Finalizada')], default='PREPARACION', max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='codigo_grupo',
            field=models.CharField(max_length=10),
        ),
    ]
