# Generated by Django 5.2.7 on 2026-05-09 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etapasJuego', '0020_teamgamesession_stage1_ranking_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamStageProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.CharField(choices=[('ROMPEHIELO', 'Rompehielo'), ('ETAPA1', 'Etapa 1'), ('HISTORIA', 'Historia'), ('ETAPA2', 'Etapa 2'), ('ETAPA2_MAPA', 'Mapa de empatía'), ('ETAPA3', 'Etapa 3'), ('ETAPA4', 'Etapa 4'), ('COEVALUACION', 'Coevaluación'), ('RESULTADOS', 'Resultados')], default='ROMPEHIELO', max_length=30)),
                ('current_route', models.CharField(default='rompehielo', max_length=120)),
                ('etapa1_completed', models.BooleanField(default=False)),
                ('etapa2_completed', models.BooleanField(default=False)),
                ('etapa3_completed', models.BooleanField(default=False)),
                ('etapa4_completed', models.BooleanField(default=False)),
                ('coevaluacion_completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_progress', to='etapasJuego.gamesession')),
                ('project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_progress', to='etapasJuego.project')),
                ('selected_challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='etapasJuego.challenge')),
                ('selected_desafio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='etapasJuego.desafio')),
                ('selected_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='etapasJuego.topic')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='etapasJuego.team')),
            ],
        ),
        migrations.CreateModel(
            name='TabletSessionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tablet_assignments', to='etapasJuego.gamesession')),
                ('tablet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='etapasJuego.tablet')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tablet_assignment', to='etapasJuego.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tablet', 'game_session'), name='unique_tablet_per_gamesession_assignment')],
            },
        ),
    ]
