# Generated by Django 5.2.7 on 2026-05-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etapasJuego', '0021_teamstageprogress_tabletsessionassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='palabras_sopa',
            field=models.JSONField(blank=True, default=list, help_text='Lista de 8–12 palabras para la sopa de letras (vacío = lista por defecto).'),
        ),
        migrations.AddField(
            model_name='pitch',
            name='campo_creatividad',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pitch',
            name='cierre',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pitch',
            name='desafio_empatia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pitch',
            name='nombre_producto',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
