# Generated by Django 5.2.7 on 2026-05-12 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etapasJuego', '0020_remove_gamesession_unique_gamesession_per_seccion_and_more'),
        ('etapasJuego', '0023_add_negociacion_fields'),
    ]

    operations = [
    ]
