MISSION_STORY = {
    "login": {
        "kicker": "Archivo 2060",
        "headline": "El miedo apago el futuro",
        "title": "Epidemia del Miedo al Emprendimiento",
        "summary": "Un mensaje cifrado advierte que el miedo a fracasar paralizo la capacidad humana de crear soluciones.",
        "mission_prompt": "Entren a la mision y activen un escuadron capaz de recuperar el Valor Emprendedor.",
        "skill": "Primer contacto",
        "objective": "Ingresar al sistema para activar un escuadron capaz de recuperar el Valor Emprendedor.",
        "gem_fact": "GEM 2024: 50% declara miedo a fracasar; solo 33% se percibe proactivo.",
        "gem": "GEM 2024: 50% declara miedo a fracasar y solo 33% se percibe proactivo para transformar oportunidades.",
        "drawer_detail": "La epidemia no comenzo como ciencia ficcion: partio como una senal de baja confianza, poca proactividad y temor al error. El juego convierte esas barreras en acciones concretas.",
        "completion_message": "Acceso concedido: el escuadron entra al origen de la epidemia.",
    },
    "home": {
        "headline": "No vienen a mirar. Vienen a restaurar.",
        "title": "Ustedes son el escuadron del pasado",
        "summary": "La UDD del futuro busca equipos capaces de entrenar habilidades que el 2060 ya dio por perdidas.",
        "mission_prompt": "Completen la ruta para acumular Energia Emprendedora antes de que la epidemia avance.",
        "skill": "Equipo · Empatia · Creatividad · Comunicacion · Apoyo",
        "objective": "Completar la ruta para acumular Energia Emprendedora antes de que la epidemia avance.",
        "gem_fact": "La intencion de emprender cayo a su nivel mas bajo en 10 años.",
        "gem": "La intencion de emprender en Chile cayo a su nivel mas bajo en 10 anos: la mision parte aqui.",
        "drawer_detail": "Cada fase del juego recupera una capacidad perdida: coordinar, entender, imaginar, comunicar y apoyar. El ranking mide energia, pero el progreso real es la transformacion del grupo.",
        "completion_message": "Ruta visible: el escuadron ya sabe que habilidades debe recuperar.",
    },
    "modalidad": {
        "kicker": "Calibracion",
        "headline": "Primero se enciende el equipo",
        "title": "Antes de actuar, deben reconocerse",
        "summary": "Un grupo indiferente se transforma en protagonista cuando decide como iniciar la colaboracion.",
        "mission_prompt": "Elijan si necesitan presentarse o activar directamente la ruleta.",
        "skill": "Confianza inicial",
        "objective": "Elegir si necesitan presentarse o activar directamente la ruleta de preguntas.",
        "gem_fact": "El miedo baja cuando hablar se vuelve seguro y compartido.",
        "gem": "El miedo se combate primero creando seguridad para hablar, escuchar y participar.",
        "drawer_detail": "La modalidad no es un tramite: define como el grupo cruza la primera barrera social. Si no se conocen, la mision necesita confianza; si se conocen, necesita foco.",
        "completion_message": "Calibracion lista: el escuadron puede iniciar la activacion.",
    },
    "rompehielo": {
        "kicker": "Fase 0",
        "headline": "De grupo a escuadron",
        "title": "Convertir desconocidos en escuadron",
        "summary": "La ruleta abre conversaciones breves para que cada integrante deje de ser espectador.",
        "mission_prompt": "Giren, respondan y pasen la tablet: todos deben activar su voz.",
        "skill": "Trabajo en equipo y comunicacion inicial",
        "objective": "Responder, escuchar y pasar la tablet para que todos entren a la historia.",
        "gem_fact": "La proactividad se entrena con una primera accion visible.",
        "gem": "La baja proactividad empieza a revertirse cuando todos toman una primera accion visible.",
        "drawer_detail": "La epidemia se alimenta del silencio. Cada respuesta breve reduce distancia social y prepara al equipo para decidir bajo tiempo.",
        "completion_message": "Escuadron activado: todos ya entraron a la mision.",
    },
    "stage1": {
        "kicker": "Fase 1",
        "headline": "Recuperen las palabras perdidas",
        "title": "Recuperar el lenguaje emprendedor",
        "summary": "La epidemia borro palabras clave para actuar juntos. Encontrarlas exige coordinacion real.",
        "mission_prompt": "Dividan busqueda, compartan pistas y completen la sopa antes del tiempo.",
        "skill": "Trabajo en equipo",
        "objective": "Dividir busquedas, compartir pistas y completar la sopa antes de que el tiempo se agote.",
        "gem_fact": "GEM 2024: solo 33% se percibe proactivo.",
        "gem": "GEM 2024: solo 33% se percibe proactivo; esta fase entrena accion coordinada.",
        "drawer_detail": "Encontrar palabras no es solo velocidad: obliga a mirar distinto, avisar hallazgos y confiar en la observacion de otros.",
        "completion_message": "Habilidad desbloqueada: trabajo en equipo.",
    },
    "story": {
        "kicker": "Archivo 2060",
        "headline": "El origen de la epidemia",
        "title": "El origen de la epidemia",
        "summary": "El miedo a emprender comenzo como una tendencia estadistica y termino apagando la imaginacion colectiva.",
        "mission_prompt": "Elijan un frente de accion y restauren habilidades perdidas con un desafio real.",
        "skill": "Valor Emprendedor",
        "objective": "Elegir un escuadron tematico y restaurar habilidades perdidas con un desafio real.",
        "gem_fact": "En 2024 ya habia miedo a fracasar, baja proactividad y menor optimismo.",
        "gem": "En 2024 ya se observaba el virus inicial: miedo a fracasar, baja proactividad y menor optimismo.",
        "drawer_detail": "El Archivo 2060 conecta la ficcion con una tendencia real: cuando las personas dejan de verse capaces, la innovacion se vuelve excepcion.",
        "completion_message": "Mision aceptada: el escuadron entra a un desafio real.",
    },
    "stage2": {
        "kicker": "Fase 2",
        "headline": "Detecten antes de proponer",
        "title": "Detectar antes de proponer",
        "summary": "El Gran Olvido hizo creer que no existian oportunidades. El escuadron debe mirar necesidades concretas.",
        "mission_prompt": "Elijan un desafio que puedan comprender, explicar y transformar.",
        "skill": "Empatia estrategica",
        "objective": "Elegir un desafio que puedan comprender, explicar y transformar en oportunidad.",
        "gem_fact": "GEM 2024: emprendimientos menos innovadores y mas reactivos al empleo.",
        "gem": "GEM 2024: los emprendimientos eran menos innovadores y muchos nacian por falta de empleo.",
        "drawer_detail": "La etapa cambia la pregunta de 'que inventamos' a 'a quien ayudamos'. Esa decision evita soluciones vacias y orienta el resto del juego.",
        "completion_message": "Desafio fijado: el equipo ya tiene una oportunidad concreta.",
    },
    "stage2_map": {
        "kicker": "Fase 2.1",
        "headline": "Escuchen la senal humana",
        "title": "Reconstruir la empatia",
        "summary": "La solucion aparece cuando el equipo entiende que siente, ve y necesita la persona afectada.",
        "mission_prompt": "Escriban evidencia breve: que piensa, teme, ve y necesita el usuario.",
        "skill": "Empatia profunda",
        "objective": "Completar respuestas concretas para que el prototipo nazca desde evidencia humana.",
        "gem_fact": "Entender al usuario reduce la percepcion de un entorno hostil.",
        "gem": "Percibir un entorno hostil reduce la accion; entender al usuario devuelve foco y sentido.",
        "drawer_detail": "La empatia no es decorar la idea: es el filtro que decide que problema vale la pena resolver y como medir si la solucion importa.",
        "completion_message": "Habilidad desbloqueada: empatia profunda.",
    },
    "stage3": {
        "kicker": "Fase 3",
        "headline": "Construyan contra el olvido",
        "title": "Materializar una idea",
        "summary": "Construir obliga a convertir conversacion en forma, evidencia y decision compartida.",
        "mission_prompt": "Prototipen con LEGO, fotografien la solucion y resuman el valor.",
        "skill": "Creatividad aplicada",
        "objective": "Prototipar con LEGO, fotografiar la solucion y resumir como responde al desafio.",
        "gem_fact": "La innovacion vuelve cuando una idea se prueba y se muestra.",
        "gem": "La innovacion vuelve cuando una idea se prueba, se muestra y se mejora con otros.",
        "drawer_detail": "El prototipo baja la idea a una forma visible. Si el equipo no puede mostrarla, probablemente aun no puede explicarla.",
        "completion_message": "Habilidad desbloqueada: creatividad aplicada.",
    },
    "stage4": {
        "kicker": "Fase 4",
        "headline": "Transmitan energia emprendedora",
        "title": "Transmitir valor",
        "summary": "El campeon no solo imagina una solucion: logra que otros entiendan por que importa.",
        "mission_prompt": "Redacten un pitch breve: problema, solucion e impacto.",
        "skill": "Comunicacion y vision de valor",
        "objective": "Redactar un pitch breve que conecte problema, solucion e impacto.",
        "gem_fact": "Emprender sigue siendo una via de desarrollo personal y profesional.",
        "gem": "Emprender sigue siendo una via de desarrollo personal, profesional y economico.",
        "drawer_detail": "Comunicar convierte el prototipo en una oportunidad compartida. El pitch debe hacer que otros quieran apoyar la solucion.",
        "completion_message": "Habilidad desbloqueada: comunicacion de valor.",
    },
    "coevaluation": {
        "kicker": "Fase 5",
        "headline": "Distribuyan energia de apoyo",
        "title": "Evaluar para fortalecer",
        "summary": "La mision no se gana aislados. Cada escuadron distribuye criterio, respeto y apoyo.",
        "mission_prompt": "Evalúen con justicia: sus puntajes fortalecen a otros escuadrones.",
        "skill": "Negociacion, criterio y feedback",
        "objective": "Asignar puntajes justos a otros equipos para reconocer valor emprendedor.",
        "gem_fact": "Las barreras personales se reducen con redes y feedback claro.",
        "gem": "Superar barreras personales y profesionales requiere redes que den feedback claro.",
        "drawer_detail": "La coevaluacion entrena criterio emprendedor: reconocer valor, argumentar apoyo y entregar feedback sin competir destructivamente.",
        "completion_message": "Energia distribuida: el ecosistema se fortalece.",
    },
    "final": {
        "kicker": "Fase 6",
        "headline": "El futuro vuelve a imaginar",
        "title": "La energia vuelve a circular",
        "summary": "El ranking reconoce a un campeon, pero todos los escuadrones entrenaron habilidades contra el miedo.",
        "mission_prompt": "Celebren, identifiquen aprendizajes y proyecten la habilidad que seguiran reforzando.",
        "skill": "Valor Emprendedor",
        "objective": "Celebrar, identificar aprendizajes y proyectar la habilidad que cada equipo seguira reforzando.",
        "gem_fact": "Capacidades percibidas y vision de largo plazo restauran la innovacion.",
        "gem": "Capacidades percibidas y vision de largo plazo son claves para restaurar la innovacion.",
        "drawer_detail": "El campeon simboliza energia emprendedora alta, pero la restauracion depende de todos: cada habilidad practicada reduce el miedo a crear.",
        "completion_message": "Mision completada: el Valor Emprendedor queda reactivado.",
    },
}


def get_story(key: str) -> dict:
    return MISSION_STORY.get(key, {})
